[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
      source ~/dotfiles/nvim/plugins/fern.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set laststatus=2
    let g:lightline = { 'colorscheme': 'wombat' }
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
      source ~/dotfiles/nvim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'thinca/vim-qfhl'

[[plugins]]
repo= 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
    nmap <Leader>t :TagbarToggle<CR>
    let g:tagbar_map_togglesort = "S"
    let g:tagbar_width = 60
'''

[[plugins]]
repo = 'eiji03aero/quick-notes'
hook_add = '''
    let g:quick_notes_directory = '~/.cache/quick-notes/'
    let g:quick_notes_suffix = 'md'
'''

# [[plugins]]
# repo = 'chrisbra/csv.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = '''
      source ~/dotfiles/nvim/plugins/vim-vsnip.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
