[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_add = '''
    autocmd FileType python map <buffer> <S-f> :call Flake8() <CR>
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'
