[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = 'c'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
    let g:jedi#completions_enabled = 0

    let g:jedi#goto_command = "<leader>d"
    let g:jedi#goto_assignments_command = "<leader>g"
    let g:jedi#goto_stubs_command = ""
    let g:jedi#goto_definitions_command = ""
    let g:jedi#documentation_command = "K"
    let g:jedi#usages_command = "<leader>n"
    let g:jedi#completions_command = ""
    let g:jedi#rename_command = "<leader>r"
'''
#
# [[plugins]]
# repo = 'nvie/vim-flake8'
# on_ft = 'python'
# hook_add = '''
#     autocmd FileType python map <buffer> <S-f> :call Flake8() <CR>
# '''
#
# [[plugins]]
# repo = 'tell-k/vim-autopep8'
# on_ft = 'python'
