[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# on_source = 'ddc.vim'
# on_event = 'InsertEnter'
hook_add = '''
    " 定義ジャンプ
    " nnoremap <C-]> :<C-u>LspDefinition<CR>
    nnoremap <LocalLeader>d :<C-u>LspDefinition<CR>
    " 定義情報のホバー表示
    nnoremap K :<C-u>LspHover<CR>
    " 名前変更
    nnoremap <LocalLeader>r :<C-u>LspRename<CR>
    " 参照検索
    nnoremap <LocalLeader>n :<C-u>LspReferences<CR>
    " Lint結果をQuickFixで表示
    nnoremap <LocalLeader>f :<C-u>LspDocumentDiagnostics<CR>
    " テキスト整形
    nnoremap <LocalLeader>s :<C-u>LspDocumentFormat<CR>
    " オムニ補完を利用する場合、定義の追加
    " set omnifunc=lsp#complete

    let g:lsp_diagnostics_enabled = 1
    let g:lsp_diagnostics_signs_enabled = 1
    let g:lsp_diagnostics_virtual_text_enabled = 0
    let g:lsp_diagnostics_echo_cursor = 1
    let g:lsp_diagnostics_highlights_enabled = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
# on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
# on_source = 'ddc.vim'
