# syntax highlighting for toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# [[plugins]]
# repo = 'kat0h/bufpreview.vim'
# on_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = '''
    let g:previm_open_cmd = 'open -a Safari'
    let g:previm_enable_realtime = 1
    let g:previm_show_header = 0
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'vim-skk/denops-skkeleton.vim'
on_event = 'InsertEnter'
hook_add = '''
    imap <C-j> <Plug>(skkeleton-enable)
    cmap <C-j> <Plug>(skkeleton-enable)

    function! s:skkeleton_init() abort
    let s:globalpath = expand('~/.config/eskk/SKK-JISYO.L')
    let s:userpath = expand('~/.config/eskk/skk-jisyo.utf8')
    call skkeleton#config({
          \ 'globalJisyo': s:globalpath,
          \ 'userJisyo': s:userpath,
          \ 'eggLikeNewline': v:true,
          \})
    endfunction
    autocmd User skkeleton-initialize-pre call s:skkeleton_init()
'''

# # nvim-lsp
# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'ddc.vim'
#
# [[plugins]]
# repo = 'matsui54/ddc-nvim-lsp-doc'
# on_source = 'ddc.vim'
# hook_source = '''
#   let g:ddc_nvim_lsp_doc_config = {
#         \ 'documentation': {
#         \    'enable': v:true,
#         \    'border': 'rounded',
#         \    'maxWidth': 100,
#         \    'winblend': 0,
#         \ },
#         \ 'signature': {
#         \    'border': 'rounded',
#         \ },
#         \ }
#   call ddc_nvim_lsp_doc#enable()
# '''
# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# on_event = 'BufEnter'
# hook_source = '''
# lua << EOF
#   local nvim_lsp = require('lspconfig')
#   local on_attach = function (client, bufnr)
#     local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
#     local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
#     local opts = { noremap=true, silent=true } 
#     buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
#     buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
#     buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
#     buf_set_keymap('n', 'gs', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
#     buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
#     buf_set_keymap('n', 'gx', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
#     buf_set_keymap('n', 'g[', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
#     buf_set_keymap('n', 'g]', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
#   end
#
#   -- require'lspconfig'.pylsp.setup{}
#
#   -- for nvim-lspinstall
#   require'lspinstall'.setup() 
#   local servers = require'lspinstall'.installed_servers()
#   for _, server in pairs(servers) do
#     require'lspconfig'[server].setup{}
#   end
# EOF
# '''
#
# [[plugins]]
# repo = 'kabouzeid/nvim-lspinstall'
# on_source = 'nvim-lspconfig'
# hook_source = '''
#   lua require'lspinstall'.setup()
# '''
# [[plugins]]
# repo = 'williamboman/nvim-lsp-installer'
