# syntax highlighting for toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# [[plugins]]
# repo = 'kat0h/bufpreview.vim'
# on_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = '''
    let g:previm_open_cmd = 'open -a Safari'
    let g:previm_enable_realtime = 1
    let g:previm_show_header = 0
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'vim-skk/denops-skkeleton.vim'
on_event = 'InsertEnter'
hook_add = '''
    imap <C-j> <Plug>(skkeleton-enable)
    cmap <C-j> <Plug>(skkeleton-enable)

    function! s:skkeleton_init() abort
    let s:globalpath = expand('~/.cache/skkeleton/SKK-JISYO.L')
    let s:userpath = expand('~/.cache/skkeleton/skk-jisyo.utf8')
    call skkeleton#config({
          \ 'globalJisyo': s:globalpath,
          \ 'userJisyo': s:userpath,
          \ 'eggLikeNewline': v:true,
          \})
    endfunction
    autocmd User skkeleton-initialize-pre call s:skkeleton_init()
'''
