[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/dotfiles/nvim/plugins/denite.rc.vim
'''

# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = '''
#     source ~/dotfiles/nvim/plugins/defx.rc.vim
# '''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
    nnoremap  <silent> <Leader>f :<C-u> Fern .<CR>
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 'colorscheme': 'wombat' }
    set laststatus=2
    " set noshowmode
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
        \ 'python': {
        \           'command': 'python3'
        \ },
        \ '_' : {
            \ 'runner' : 'vimproc',
            \ 'runner/vimproc/updatetime' : 40,
            \ 'outputter/buffer/running_mark' : 'RUN',
            \ 'outputter' : 'error',
            \ 'outputter/error/success' : 'buffer_legacy',
            \ 'outputter/error/error'   : 'quickfix',
            \ 'outputter/buffer_legacy/split' : ':botright 8sp',
        \ }
    \}

    let g:quickrun_no_default_key_mappings = 1
    nnoremap <Leader>e :cclose<CR>:write<CR>:QuickRun<CR>
'''

[[plugins]]
repo= 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
    nmap <Leader>t :TagbarToggle<CR>
    let g:tagbar_map_togglesort = "S"
    let g:tagbar_width = 60
'''

[[plugins]]
repo = 'eiji03aero/quick-notes'
hook_add = '''
    let g:quick_notes_directory = '~/.cache/quick-notes/'
    let g:quick_notes_suffix = 'md'
'''
