# ddc related plugins
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_source = '''
    " <TAB> completion.
    inoremap <silent><expr> <TAB>
    \ pumvisible() ? '<C-n>' :
    \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
    \ '<TAB>' : ddc#manual_complete()
    " <S-TAB> completion back. 
    inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'
    " global settings
    call ddc#custom#patch_global('sources', ['ddc-vim-lsp','around','tmux'])
    call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \       'matchers': ['matcher_head'],
      \       'sorters': ['sorter_rank'],
      \      },
      \ 'ddc-vim-lsp': {
      \       'matchers': ['matcher_head'],
      \       'mark': 'lsp',
      \       'forceCompletionPattern': "\\.|:\\s*|->",
      \                },
      \})

    " Change source options
    call ddc#custom#patch_global('sourceOptions', {
      \ 'around': {'mark': 'A'},
      \ 'tmux': {'mark': 'T'},
      \})
    call ddc#custom#patch_global('sourceParams', {
      \ 'around': {'maxSize': 500},
      \})

    call ddc#enable()
'''

# ddc-sources
[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'delphinus/ddc-tmux'
on_source = 'ddc.vim'

# ddc-filters
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'
